### ISSUE TITLE
error about plot_yolo_log.py

### ISSUE THREAD

**Issue by zxh666** [Jumabek/darknet_scripts#18]
@Jumabek  Hi 
i have something about the  plot_yolo_log.py 
zxh@k40-2:~/darknet/darknet_scripts$ python plot_yolo_log.py /home/zxh/darknet/log/tiny-yolo-voc-train.log
Traceback (most recent call last):
  File "plot_yolo_log.py", line 46, in <module>
    main(sys.argv)
  File "plot_yolo_log.py", line 33, in main
    loss.append(float(args[2]))
ValueError: could not convert string to float: weights

**Comment by Jumabek** [comment]
Hi @zxh666 ,
I think you train.log file is in a different format.
Could you post the contents of it?
